Backport `FindCUDAToolkit` from CMake 3.31
rapidsai/kvikio pull request #550
Opened 2024-11-14 16:39 UTC by KyleFromNVIDIA

Backport to get
https://gitlab.kitware.com/cmake/cmake/-/commit/b38a8e77cb3c8401b3022a68f07a4fd77b290524, so that `find_library()` finds `libcufile` correctly.

2024-11-14 16:58 UTC, bdice approved these changes

2024-11-14 19:01 UTC, vyasr requested changes
Do we need to copy in a license file before we can vendor CMake code directly like this?

2024-11-14 21:59 UTC, vyasr approved these changes

2024-11-15 15:15 UTC, KyleFromNVIDIA commented
/merge

2024-11-15 15:15 UTC, merged